1.Program Declaration & Data Definitions
REPORT ZGSR_SALES_ALV.
 
* Type pools for ALV
TYPE-POOLS: SLIS.
 
* SAP Standard Table declarations
TABLES: VBAK, VBAP, KNA1.
 
* Custom structure for output
TYPES: BEGIN OF TY_OUTPUT,
         VBELN  TYPE VBAK-VBELN,
         ERDAT  TYPE VBAK-ERDAT,
         KUNNR  TYPE VBAK-KUNNR,
         NAME1  TYPE KNA1-NAME1,
         MATNR  TYPE VBAP-MATNR,
         ARKTX  TYPE VBAP-ARKTX,
         KWMENG TYPE VBAP-KWMENG,
         NETWR  TYPE VBAK-NETWR,
         WAERK  TYPE VBAK-WAERK,
         VKORG  TYPE VBAK-VKORG,
         AUART  TYPE VBAK-AUART,
         STATUS TYPE CHAR20,
         COLOR  TYPE LVC_T_SCOL,
       END OF TY_OUTPUT.
 
* Internal Tables
DATA: IT_OUTPUT  TYPE STANDARD TABLE OF TY_OUTPUT,
      WA_OUTPUT  TYPE TY_OUTPUT.
DATA: IT_VBAK    TYPE STANDARD TABLE OF VBAK,
      WA_VBAK    TYPE VBAK.
DATA: IT_VBAP    TYPE STANDARD TABLE OF VBAP,
      WA_VBAP    TYPE VBAP.
DATA: WA_KNA1    TYPE KNA1.




2.Selection Screen

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
  SELECT-OPTIONS: S_ERDAT FOR VBAK-ERDAT,
                  S_VKORG FOR VBAK-VKORG,
                  S_KUNNR FOR VBAK-KUNNR,
                  S_MATNR FOR VBAP-MATNR,
                  S_AUART FOR VBAK-AUART.
SELECTION-SCREEN END OF BLOCK B1.


3.Data Retrieval Logic
START-OF-SELECTION.
  SELECT * FROM VBAK
    INTO TABLE IT_VBAK
    WHERE ERDAT IN S_ERDAT
      AND VKORG IN S_VKORG
      AND KUNNR IN S_KUNNR
      AND AUART IN S_AUART.

  IF IT_VBAK IS INITIAL.
    MESSAGE 'No sales orders found.'
            TYPE 'I' DISPLAY LIKE 'W'.
    STOP.
  ENDIF.

  LOOP AT IT_VBAK INTO WA_VBAK.
    SELECT * FROM VBAP INTO TABLE IT_VBAP
      WHERE VBELN = WA_VBAK-VBELN AND MATNR IN S_MATNR.

    LOOP AT IT_VBAP INTO WA_VBAP.
      SELECT SINGLE * FROM KNA1 INTO WA_KNA1
        WHERE KUNNR = WA_VBAK-KUNNR.

      CLEAR WA_OUTPUT.
      WA_OUTPUT-VBELN  = WA_VBAK-VBELN.
      WA_OUTPUT-ERDAT  = WA_VBAK-ERDAT.
      WA_OUTPUT-KUNNR  = WA_VBAK-KUNNR.
      WA_OUTPUT-NAME1  = WA_KNA1-NAME1.
      WA_OUTPUT-MATNR  = WA_VBAP-MATNR.
      WA_OUTPUT-ARKTX  = WA_VBAP-ARKTX.
      WA_OUTPUT-KWMENG = WA_VBAP-KWMENG.
      WA_OUTPUT-NETWR  = WA_VBAK-NETWR.
      WA_OUTPUT-WAERK  = WA_VBAK-WAERK.
      WA_OUTPUT-VKORG  = WA_VBAK-VKORG.
      WA_OUTPUT-AUART  = WA_VBAK-AUART.

      CASE WA_VBAK-GBSTK.
        WHEN 'A'. WA_OUTPUT-STATUS = 'Open'.
        WHEN 'B'. WA_OUTPUT-STATUS = 'In Process'.
        WHEN 'C'. WA_OUTPUT-STATUS = 'Delivered'.
        WHEN 'D'. WA_OUTPUT-STATUS = 'Billed'.
        WHEN OTHERS. WA_OUTPUT-STATUS = 'Unknown'.
      ENDCASE.

      APPEND WA_OUTPUT TO IT_OUTPUT.
    ENDLOOP.
  ENDLOOP.

4.Field Catalog + Layout

DATA: IT_FIELDCAT TYPE LVC_T_FCAT,
      WA_FIELDCAT TYPE LVC_S_FCAT,
      WA_LAYOUT   TYPE LVC_S_LAYO.
 
FORM BUILD_FIELDCAT.
  DEFINE ADD_FIELD.
    CLEAR WA_FIELDCAT.
    WA_FIELDCAT-FIELDNAME = &1.
    WA_FIELDCAT-COLTEXT   = &2.
    WA_FIELDCAT-OUTPUTLEN = &3.
    IF &4 = 'X'. WA_FIELDCAT-DO_SUM = 'X'. ENDIF.
    APPEND WA_FIELDCAT TO IT_FIELDCAT.
  END-OF-DEFINITION.

  ADD_FIELD 'VBELN'  'Sales Order'     12 ''.
  ADD_FIELD 'ERDAT'  'Order Date'      10 ''.
  ADD_FIELD 'KUNNR'  'Customer No'     10 ''.
  ADD_FIELD 'NAME1'  'Customer Name'   30 ''.
  ADD_FIELD 'MATNR'  'Material'        18 ''.
  ADD_FIELD 'ARKTX'  'Description'     30 ''.
  ADD_FIELD 'KWMENG' 'Quantity'        10 ''.
  ADD_FIELD 'NETWR'  'Net Value'       15 'X'.
  ADD_FIELD 'WAERK'  'Currency'         5 ''.
  ADD_FIELD 'VKORG'  'Sales Org'        6 ''.
  ADD_FIELD 'STATUS' 'Order Status'    20 ''.
ENDFORM.
 
FORM BUILD_LAYOUT.
  WA_LAYOUT-ZEBRA      = 'X'.
  WA_LAYOUT-CWIDTH_OPT = 'X'.
  WA_LAYOUT-SEL_MODE   = 'A'.
  WA_LAYOUT-INFO_FNAME = 'COLOR'.
ENDFORM.


5.ALV Grid Display
DATA: GO_CONTAINER TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      GO_GRID      TYPE REF TO CL_GUI_ALV_GRID.
 
CALL SCREEN 100.
 
MODULE STATUS_0100 OUTPUT.
  PERFORM BUILD_FIELDCAT.
  PERFORM BUILD_LAYOUT.

  CREATE OBJECT GO_CONTAINER
    EXPORTING CONTAINER_NAME = 'MAIN_CONTAINER'.

  CREATE OBJECT GO_GRID
    EXPORTING I_PARENT = GO_CONTAINER.

  CALL METHOD GO_GRID->SET_TABLE_FOR_FIRST_DISPLAY
    EXPORTING
      I_STRUCTURE_NAME = 'TY_OUTPUT'
      IS_LAYOUT        = WA_LAYOUT
    CHANGING
      IT_OUTTAB        = IT_OUTPUT
      IT_FIELDCATALOG  = IT_FIELDCAT.
ENDMODULE.
